### ISSUE TITLE
`Can't connect to local MySQL server through socket` when restarting rPi

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/nextcloudpi#1127]
After restarting the raspberry, NextCloudPi usually has the following error:
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)`. The server is not available then, but it's docker status is `Up`.

A `docker restart <nextcloudpi_container>` resolves the issue. Then it starts as expected. 

**System information**
Raspberry Pi4
NextCloudPi version: `v1.25.0`
Docker image: `NextCloudPi_docker_03-20-20` (armhf)

The volume is mounted (btw. data is stored on a external disk):
```
volumes:
      - /mnt/hdd1/ncData:/data
      - /etc/localtime:/etc/localtime:ro
```

### 2 questions
1. Any ideas why this could happen?
2. Shouldn't the container exit if it can't connect to the DB? Then my restart policy could handle the issue.

**Comment by ovpc** [comment]
Looks like db is on external too and not mounted yet (fstab) when docker starts. Should use forum tho, Github is for development, discussing bugs and documentation only.

**Comment by hunhejj** [comment]
Because of the mounted volume (see above) the db is probably on the external drive too, yes.

**Comment by hunhejj** [comment]
Isn't it a bug that the container seems to be up although the DB was not started?

**Comment by ovpc** [comment]
Closing this, no-one has reproduced this afaik.

**Comment by Coernel82** [comment]
@hunhejj Is it a Rapsberry Pi 4 with **8 GB**? I get the suspicion that the
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
ineed is a bug and that this thread needs to be reopened. [This source](https://forum-raspberrypi.de/forum/thread/47927-rpi-4-8gb-inkompatibel-mit-nextcloud/) also indicates it should be a real problem - but for the 8 GB version only.

**Comment by hunhejj** [comment]
I had the issue with a raspberry pi 4 with 4GB

**Comment by ovpc** [comment]
Reopening an issue does not make it a bug.
Anyone else reproducing this ?  on rpi4-8Gb, its a docker container too, which add's another layer

**Comment by markgllin** [comment]
I'm currently running into the same issue on RPi4-2GB in the docker container.

From `docker logs`:
```
2020-07-14 23:01:32 0 [Note] mysqld (mysqld 10.3.22-MariaDB-0+deb10u1) starting as process 106 ...
Starting Redis
Starting Cron
Starting Postfix
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)
Init done
```

my `docker-compose.yml`:
```
services:
  nextcloud:
    image: ownyourbits/nextcloudpi-armhf
    container_name: nextcloud
    volumes:
      - ncdata:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 81:80
      - 445:443
      - 4443:4443

volumes:
   ncdata:
     driver: local
     driver_opts:
       type: 'none'
       o: 'bind'
       device: '/mnt/docker/docker/data'
```
what's curious is that it ran successfully the first time i did a `docker-compose up -d`, correctly creating the bindmount where the db is stored. 

`ncp-report` didn't seem to capture anything 
```
root@11eed60a5e62:/# ncp-report
<--! Paste this in GitHub report -->

<details>
<summary>NextCloudPi diagnostics</summary>

```

will continue debugging and report back if i find anything
