### ISSUE TITLE
Nextcloud version in latest Docker image published doesn't match

### ISSUE THREAD

**Issue by jush** [nextcloud/nextcloudpi#1256]
I used the following docker compose yaml to start a fresh nextcloud container:
```
version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-arm64
    command: "192.168.1.162"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ./data:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi
    restart: unless-stopped
```
Which should use this [docker image](https://hub.docker.com/layers/ownyourbits/nextcloudpi/latest/images/sha256-93b8c5a846add666db340a6740fce9927675f00bbb078c6245360db3672c1803).
In the system info interface I see:
```
NextCloudPi version | v1.34.6

Nextcloud version | 18.0.3.0
```

Unfortunately I run into the issue reported in #1250.

If I read the [Changelod.md](https://github.com/nextcloud/nextcloudpi/blob/b978184ce6a5e7f7171bb73cdce8009367cfdaa9/changelog.md) file properly Nextcloud version should be `20.0.4` since v1.34.0 instead of `18.0.3.0`

Then I decided to build the docker image myself by cloning this repo and running command:
```
sudo docker build --progress=plain . -f docker/nextcloudpi/Dockerfile -t jush/nextcloudpi-arm64:latest --build-arg release=buster --build-arg arch=arm64 --build-arg ncp_ver=1.34.6
```

And the system info for that container is indeed showing Nextcloud version `20.0.4.0 ` and it initializes properly (that is, I can't replicate issue #1250)

The bug seems to be that docker images published are somehow using an old Nextcloud version.
