### ISSUE TITLE
Initialization process of NexcloudPi ends in eternal loop

### ISSUE THREAD

**Issue by JanBrink42** [nextcloud/nextcloudpi#1280]
Here is a bug report on the initialization process of NexcloudPi:

On my Raspberry Pi4, I started a container based on the following docker-compose.yaml:
```
version: '3'
services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf
    command: "${IP}"
    ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ncdata4:/data
     - /etc/localtime:/etc/localtime:ro
    container_name: nextcloudpi

volumes:
  ncdata4:
```
IP is set to the local IP address of the Raspberry Pi.

After starting, I can access the web interface, receiving two passwords, and I can log into the admin area (Port 4443).
But when I navigate to the nextcloud itself (Port 80 or 443), a page telling the following is shown:
```
Initializing NextCloudPi for the first time
Please wait...
```
This site is refreshing itself in an eternal loop. Thus, Nextcloud cannot be used.
