### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloudpi#1534]
**Description**  
Adding a docker-compose file that allows users to understand the environment variables applied to the Docker image.

**Example**  
Instead of `docker run yadayda` you can optionally use a docker-compose.yml file.  The first advantage is you will not forget what you entered as part of your run command.  You'll also be able to immediately confirm exactly how your image was setup.
- Volume locations (where data directory resides)
- Any changes you made when running the image can be verified.
- It makes docker easier to understand.

`docker run -d -p 4443:4443 -p 443:443 -p 80:80 -v /path/to/ncdata:/data --name nextcloudpi ownyourbits/nextcloudpi DOMAIN`

```
version: '3.3'
services:
    nextcloudpi:
        container_name: nextcloudpi
        image: ownyourbits/nextcloudpi
        ports:
            - '4443:4443'
            - '443:443'
            - '80:80'
        volumes:
            - '/path/to/ncdata:/data'
        restart: unless-stopped
```
