### ISSUE TITLE
[docker] Panel password doesn't persist

### ISSUE THREAD

**Issue by lil5** [nextcloud/nextcloudpi#541]
After setting everything up

docker-compose.yml
```yml
version: '3'

services:
  ncp:
    image: ownyourbits/nextcloudpi-armhf
    restart: unless-stopped
    volumes:
      - /mnt/Data/ncp:/data
    ports:
      - 443:443
      - 4443:4443
```

I run the following:

```
docker-compose down
docker-compose up -d
```

...and I can't log in to the Panel:
(using the previous default user: `ncp`, pass: [44 char random] )
